[package]
name = "srmp-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
queues = "1.0.2"
hypergraph = "2.1.2"
petgraph = "0.6.5"
bit-vec = "0.7.0"
ndarray = "0.15.6"
log = "0.4.22"
env_logger = "0.11.3"
